## Home assignment 1

Asher Fredman<br>
Shachar Schnapp

In [21]:
import numpy as np
from IPython.display import Math

### 1. Vector norms, matrix norms, and inner products.

#### (a) For two matrices $A,B\in \mathbb{R}^{mxn}$, show that $\langle A[:],B[:] \rangle = trace(A^TB)$

Answer:<br>
$\langle A[:],B[:] \rangle = \sum_{j=1}^{n}\sum_{i=1}^{m} A_{ij}\times B_{ij} = trace(A^TB)$

Explanation:<br>
The first equation holds since the $A[:]$ operator just creates a vector stacking the $n$ columns of $A$, and by difinition of the regular vector dot product we sum over the multiplication of the corisponding $m\times n$ entries in $A$ and $B$.<br>
The second equation holds since the trace of $A^TB$ will return the sum of the entries where each entry is the dot product of each column in A with the corresponding column in B.  

#### (b) Find a $x_1$ vector that maximizes $\ell_1$ and a $x_\infty$ vector that maximizes $\ell_\infty$ for the matrix:

$A = \begin{bmatrix}
1 & 2 & 3 & 4 \\
2 & 4 & -4 & 8 \\
-5 & 4 & 1 & 5 \\
5 & 0 & -3 & -7 
\end{bmatrix}$ .

Answer:<br>
For the $x_1$, by definition of $\begin{Vmatrix} A \end{Vmatrix}_1$ we look for the column for which summing over the absolute value of it's entries returns the maximum value. for the given $A$ this will output $\lvert 4 \rvert + \lvert 8 \rvert + \lvert 5 \rvert + \lvert -7 \rvert = 24$.<br>
For the $x_\infty$, by definition of $\begin{Vmatrix} A \end{Vmatrix}_\infty$ we look for the row for which summing over the absolute value of it's entries returns the maximum value. for the given $A$ this will output $\lvert 2 \rvert + \lvert 4 \rvert + \lvert -4 \rvert + \lvert 8 \rvert = 18$. 

### 2. Least Squares

#### (a) Find the best approximation in a least square sense for satisfying the linear system $Ax = b$ where 

$A = \begin{bmatrix}
2 & 1 & 2 \\
1 & -2 & 1 \\
1 & 2 & 3 \\
1 & 1 & 1 
\end{bmatrix}$ and $b = \begin{bmatrix}
6 \\
1 \\
5 \\
2 
\end{bmatrix}$.

#### Write the normal equations and solve the problem using them. You may use a computer and provide the code.

Answer:<br>
The normal equation is given by $A^TAx = A^Tb$ and since A isn't singular we can take it's inverse and get $\hat{x} = (A^TA)^{-1}A^Tb$.<br>Using the following code we get:

In [35]:
A = np.array([[2,1,2],[1,-2,1],[1,2,3],[1,1,1,]])
b = np.array([[6],[1],[5],[2]])

In [36]:
ATA = A.T.dot(A) 
ATA_inv = np.linalg.inv(ATA)
ATb = A.T.dot(b)
x = ATA_inv.dot(ATb)

$\hat{x}$ is:

In [39]:
print(x)

[[1.7]
 [0.6]
 [0.7]]


#### (b) Compute the residual of the least squares system $r = Ax − b$, with $x$ that you found in the previous section. Show that $A^⊤r = 0$. Is that surprising?
Answer:

In [11]:
r = A.dot(x)-b

The residual $(r)$ is:

In [40]:
print(r)

[[-6.00000000e-01]
 [ 2.00000000e-01]
 [-3.55271368e-15]
 [ 1.00000000e+00]]


If we calculate $A^⊤r$ we get vector very close to the zero vector:

In [41]:
print(A.T.dot(r))

[[-1.24344979e-14]
 [-1.06581410e-14]
 [-1.95399252e-14]]


This is not suprising, since $A^⊤r$ is exactly the normal equation, which should equal zero. 

#### (c) Find the least squares solution of the system in (a), but now find a solution for which the first equation is almost exactly satisfied satisfied (let’s say, such that $\lvert r_1 \rvert < 10^{−3}$).

Answer:
We will solve the weighted least squares problem with the following <br><br>weight matrix $w$:

In [61]:
W = np.eye(4)
W[0,0] = 1000
print(W)

[[1000.    0.    0.    0.]
 [   0.    1.    0.    0.]
 [   0.    0.    1.    0.]
 [   0.    0.    0.    1.]]


In [45]:
ATWA = A.T.dot(W).dot(A) 
ATWA_inv = np.linalg.inv(ATWA)
ATWb = A.T.dot(W).dot(b)
x_w = ATWA_inv.dot(ATWb)
r_w = A.dot(x_w)-b

We now get the following residual vector:

In [46]:
print(r_w)

[[-8.07412821e-04]
 [ 2.69137606e-01]
 [-1.36424205e-12]
 [ 1.34568803e+00]]


### 3. Regularized Least Squares and SVD

For $A \in \mathbb{R}^{mxn}$, we saw there exist orthogonal matrices $U$ and $V$, such that
$A=UΣV^⊤$ (the SVD factorization of $A$), $Σ=diag(σ_1,σ_2,...,σ_p)$ $p=min(m,n)$,
where $σ_1 ≥ σ_2 ≥ σ_3 ≥ ... ≥ σ_p ≥ 0$.<br>
In our solutions we will shift between the using the full and economic versions of the SVD factorization. 

#### (a) Using the normal equations and the SVD decompositon, show that the solution of the LS problem $argmin_x\{∥Ax − b∥_2^2\}$, is given by $\hat{x} = (A^⊤A)^{−1}A^⊤b = VΣ^{−1}U^⊤b$.
Answer:

$\hat{x} = (A^⊤A)^{−1}A^⊤b$

$A^⊤A = (UΣV^⊤)^⊤U\Sigma V^⊤ = V\Sigma^\top U^\top U\Sigma V^\top = V\Sigma^\top \Sigma V^\top$
$A^⊤b = (UΣV^⊤)^\top b = V\Sigma^\top U^\top b$

$\Rightarrow \hat{x} = 
(V\Sigma^\top \Sigma V^\top)^{-1}V\Sigma^\top U^\top b = 
V\Sigma^{-1}\Sigma^{\top^{-1}} V^{-1}V\Sigma^\top U^\top b = 
V\Sigma^{-1}\Sigma^{\top^{-1}}\Sigma^\top U^\top b = 
VΣ^{−1}U^⊤b$

#### (b) Show that $V Σ^{−1}U^⊤ =  \sum_{i=1}^{min(m,n)} σ^{−1}_iv_iu^⊤_i$ , where $u_i$ and $v_i$ are the columns of U and V respectively
Answer:

$V Σ^{−1}U^⊤ = $

$= \begin{bmatrix}
\sigma_1^{-1}v_{11} & \sigma_2^{-1}v_{12} & \dots  & \sigma_p^{-1}v_{1p} \\
\sigma_1^{-1}v_{21} & \sigma_2^{-1}v_{22} & \dots  & \sigma_p^{-1}v_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
\sigma_1^{-1}v_{n1} & \sigma_2^{-1}v_{n2} & \dots  & \sigma_p^{-1}v_{np}
\end{bmatrix}
\begin{bmatrix}
u_{11} & u_{12} & \dots  & u_{1p} \\
u_{21} & u_{22} & \dots  & u_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
u_{m1} & u_{m2} & \dots  & u_{mp}
\end{bmatrix}^\top$

$=\begin{bmatrix}
(\sigma_1^{-1}v_{11}u_{11} + \sigma_2^{-1}v_{12}u_{12} +\dots+ \sigma_p^{-1}v_{1p}u_{1p}) & \dots & (\sigma_1^{-1}v_{11}u_{m1} + \sigma_2^{-1}v_{12}u_{m2} +\dots+ \sigma_p^{-1}v_{1p}u_{mp}) \\
(\sigma_1^{-1}v_{21}u_{11} + \sigma_2^{-1}v_{22}u_{12} +\dots+ \sigma_p^{-1}v_{2p}u_{1p}) & \dots & (\sigma_1^{-1}v_{21}u_{m1} + \sigma_2^{-1}v_{22}u_{m2} +\dots+ \sigma_p^{-1}v_{2p}u_{mp}) \\
\vdots & \ddots & \vdots \\
(\sigma_1^{-1}v_{n1}u_{11} + \sigma_2^{-1}v_{n2}u_{12} +\dots+ \sigma_p^{-1}v_{np}u_{1p}) & \dots & (\sigma_1^{-1}v_{n1}u_{m1} + \sigma_2^{-1}v_{n2}u_{m2} +\dots+ \sigma_p^{-1}v_{np}u_{mp}) \\
\end{bmatrix}$

$=\begin{bmatrix}
\sigma_1^{-1}v_{11}u_{11} & \dots & \sigma_1^{-1}v_{11}u_{m1} \\
\sigma_1^{-1}v_{21}u_{11} & \dots & \sigma_1^{-1}v_{21}u_{m1} \\
\vdots & \ddots & \vdots \\
\sigma_1^{-1}v_{n1}u_{11} & \dots & \sigma_1^{-1}v_{n1}u_{m1} \\
\end{bmatrix}+
\begin{bmatrix}
\sigma_2^{-1}v_{12}u_{12} & \dots & \sigma_2^{-1}v_{12}u_{m2} \\
\sigma_2^{-1}v_{22}u_{12} & \dots & \sigma_2^{-1}v_{22}u_{m2} \\
\vdots & \ddots & \vdots \\
\sigma_2^{-1}v_{n2}u_{12} & \dots & \sigma_2^{-1}v_{n2}u_{m2} \\
\end{bmatrix}+ \dots +
\begin{bmatrix}
\sigma_p^{-1}v_{1p}u_{1p} & \dots & \sigma_p^{-1}v_{1p}u_{mp} \\
\sigma_p^{-1}v_{2p}u_{1p} & \dots & \sigma_p^{-1}v_{2p}u_{mp} \\
\vdots & \ddots & \vdots \\
\sigma_p^{-1}v_{np}u_{1p} & \dots & \sigma_p^{-1}v_{np}u_{mp} \\
\end{bmatrix}$

$= σ^{−1}_1v_1u^⊤_1 + σ^{−1}_2v_2u^⊤_2 + \dots σ^{−1}_pv_pu^⊤_p
= \sum_{n=1}^{min(m,n)} σ^{−1}v_iu^⊤_i$

#### (c) Using the previous two sections show: 
$\hat{x} = \sum_{i=1}^{min(m,n)} \frac{1}{σ_i}(u^⊤_ib)v_i$.<br><br>
Answer:

$\hat{x} = V Σ^{−1}U^⊤b = $

$= \begin{pmatrix} \begin{bmatrix}
v_{11} & v_{12} & \dots  & v_{1p} \\
v_{21} & v_{22} & \dots  & v_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
v_{n1} & v_{n2} & \dots  & v_{np}
\end{bmatrix}
\begin{bmatrix}
\sigma_1^{-1} & & \\
& \sigma_2^{-1} & & \\
& & \ddots & \\
& & & \sigma_p^{-1}
\end{bmatrix}
\end{pmatrix}
\begin{pmatrix}
\begin{bmatrix}
u_{11} & u_{12} & \dots  & u_{1p} \\
u_{21} & u_{22} & \dots  & u_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
u_{m1} & u_{m2} & \dots  & u_{mp}
\end{bmatrix}^\top
\begin{bmatrix}
    b_1 \\
    b_2 \\
    \vdots \\
    b_n 
\end{bmatrix}
\end{pmatrix}$


$= \begin{bmatrix}
\sigma_1^{-1}v_{11} & \sigma_2^{-1}v_{12} & \dots  & \sigma_p^{-1}v_{1p} \\
\sigma_1^{-1}v_{21} & \sigma_2^{-1}v_{22} & \dots  & \sigma_p^{-1}v_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
\sigma_1^{-1}v_{n1} & \sigma_2^{-1}v_{n2} & \dots  & \sigma_p^{-1}v_{np}
\end{bmatrix} 
\begin{bmatrix}
    u^⊤_1b \\
    u^⊤_2b \\
    \vdots \\
    u^⊤_pb
\end{bmatrix} = \begin{bmatrix}
    \sum_{i=1}^{p}(\frac{1}{σ_i}v_{1i}u^⊤_ib) \\
    \sum_{i=1}^{p}(\frac{1}{σ_i}v_{2i}u^⊤_ib) \\
    \vdots \\
    \sum_{i=1}^{p}(\frac{1}{σ_i}v_{pi}u^⊤_ib)
\end{bmatrix}$

$= \frac{1}{σ_1}u^⊤_1b\begin{bmatrix}
    v_{11} \\
    v_{21} \\
    \vdots \\
    v_{n1}
\end{bmatrix} +
\frac{1}{σ_2}u^⊤_2b\begin{bmatrix}
    v_{12} \\
    v_{22} \\
    \vdots \\
    v_{n2}
\end{bmatrix} +
\frac{1}{σ_p}u^⊤_pb\begin{bmatrix}
    v_{1p} \\
    v_{2p} \\
    \vdots \\
    v_{np}
\end{bmatrix}
$

$= \sum_{i=1}^{min(m,n)} \frac{1}{σ_i}(u^⊤_ib)v_i$

#### (d) Consider a full SVD, where $U \in \mathbb{R}^{mxm}$ so we have $m$ vectors $u_i$ that span the whole $\mathbb{R}^{m}$ space. Assume that $b =  \sum_{i=1,..,m} α_iu_i$ for some $α_i$. Show that $\hat{x} = \sum_{i=1}^{min(m,n)} \frac{1}{\sigma_i}α_iv_i$.<br>
Answer:

Given the previous paragraph, it will be enough to show that for $i \in \{1,..,m\},$ $u^⊤_ib = \alpha_i$, and then placing $\alpha_i$ in the previous result will give the desired answer.

$u^⊤_ib = u^⊤_i(\sum_{j=1}^{m} \alpha_ju_j) =$ 
$= \alpha_1u^\top_iu_1 + \alpha_2u^\top_iu_2 + \dots + \alpha_iu^\top_iu_i + \dots + \alpha_mu^\top_iu_m =$
$= \alpha_1\times 0 + \alpha_2\times 0 + \dots + \alpha_i\times 1 + \dots + \alpha_m\times 0
= \alpha_i.$

#### (e) Show that the solution of the regularized LS problem $argmin_x\{∥Ax − b∥_2^2 + \lambda∥x∥_2^2\}$, is given by the solution of the system $(A^⊤A + \lambda I)x = A^⊤b$.
Answer:

First we'll prove that the matrix $(A^⊤A + \lambda I)$ is SPD for any $\lambda > 0$.<br>
Proof:<br>
1) $A^⊤A$ is symetric: $(A^⊤A)^⊤ = A^⊤A^{⊤^⊤} = A^⊤A$.<br>
2) $A^⊤A$ is PSD (i.e., $\forall x\neq 0$ $x^\top A^⊤Ax \geq 0$):<br>
We'll look at the $\ell_2$ norm of $Ax$. $ ∥ Ax ∥_2 = \sqrt{(Ax)^⊤(Ax)} = \sqrt{(x^⊤A^⊤Ax)} \Rightarrow (x^⊤A^⊤Ax) \geq 0$.<br>
3) $\lambda I$ is PD since it is diagonal with values $> 0$ on the diagonal and of course $x^⊤(\lambda I)x = \lambda x^⊤x_{(> 0)}$ for every $x>0$.<br>
4) $x^⊤(A^⊤A + \lambda I)x = x^⊤A^⊤Ax_{(\geq 0)} + x^⊤(\lambda I)x_{(>0)} > 0$. And so $(A^⊤A + \lambda I)$ is PD.
<br><br>
Since $(A^⊤A + \lambda I)$ is PD, than it is invertible (since all eigenvalues are greater than zero and the determenant is the multiplication of the eigen values and so $det(A^⊤A + \lambda I) > 0$), than the solution of $(A^⊤A + \lambda I)x = A^⊤b$ is $x = (A^⊤A + \lambda I)^{-1}A^⊤b$.
<br><br>
We'll define $\underset{(m+n)\times n}{M}:=\begin{bmatrix} A \\ \sqrt{\lambda}I \end{bmatrix}$ 
, $\underset{(m+n)\times 1}{L}:=\begin{bmatrix} b \\ 0 \end{bmatrix}$

$f(x) = \hat{x} = argmin_x\{∥Ax − b∥_2^2 + \lambda∥x∥_2^2\} = $

$= argmin_x\{∥Mx − L∥_2^2\} = (Mx-L)^\top(Mx-L) =$

$= x^\top M^\top Mx - 2L^\top Mx +L^\top L$

$\nabla f(x) = 2M^\top Mx - 2M^\top L = $

$= \begin{pmatrix} \begin{bmatrix} A \\ \sqrt{\lambda}I \end{bmatrix}^\top \begin{bmatrix} A \\ \sqrt{\lambda}I \end{bmatrix}\end{pmatrix}^{-1}\begin{bmatrix} A \\ \sqrt{\lambda}I \end{bmatrix}^\top\begin{bmatrix} b \\ 0 \end{bmatrix} =$

$= (A^⊤A + \lambda I)^{-1}A^⊤b$.


#### (f) Given the previous sections, show that the solution of the regularized LS problem is given by 

$\sum_{i=1}^{min(m,n)} \frac{σ_i}{σ^2_i+\lambda}\alpha_iv_i$.

Answer:

$\hat{x} = 
(V\Sigma^\top \Sigma V^\top + \lambda I)^{-1}V\Sigma^\top U^\top b$

$\Rightarrow V^{-1}\hat{x} = 
(V\Sigma^2 + \lambda IV)^{-1}V\Sigma^\top U^\top b = (V\Sigma^2 + V\lambda I)^{-1}V\Sigma^\top U^\top b$

$\Rightarrow V^{-1}\hat{x} = 
(\Sigma^2 + \lambda I)^{-1}V^{-1}V\Sigma^\top U^\top b = (\Sigma^2 + \lambda I)^{-1}\Sigma^\top U^\top b$

$\Rightarrow \hat{x} = 
V(\Sigma^2 + \lambda I)^{-1}\Sigma^\top U^\top b$

Since $(\Sigma^2 + \lambda I)^{-1}\Sigma^\top$ is just $diag(\frac{σ_i}{σ^2_i+\lambda})$ for $i \in [1,\dots ,p]$
Then we get:<br>
$\hat{x} = 
V(\Sigma^2 + \lambda I)^{-1}\Sigma^\top U^\top b = $

$= \begin{pmatrix} \begin{bmatrix}
v_{11} & v_{12} & \dots  & v_{1p} \\
v_{21} & v_{22} & \dots  & v_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
v_{n1} & v_{n2} & \dots  & v_{np}
\end{bmatrix}
\begin{bmatrix}
\frac{σ_1}{σ^2_1+\lambda} & & \\
& \frac{σ_2}{σ^2_2+\lambda} & & \\
& & \ddots & \\
& & & \frac{σ_p}{σ^2_p+\lambda}
\end{bmatrix}
\end{pmatrix}
\begin{pmatrix}
\begin{bmatrix}
u_{11} & u_{12} & \dots  & u_{1p} \\
u_{21} & u_{22} & \dots  & u_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
u_{m1} & u_{m2} & \dots  & u_{mp}
\end{bmatrix}^\top
\begin{bmatrix}
    b_1 \\
    b_2 \\
    \vdots \\
    b_n 
\end{bmatrix}
\end{pmatrix}$


And picking on answers to previous sections we obtaion that this results in $\sum_{i=1}^{min(m,n)} \frac{σ_i}{σ^2_i+\lambda}\alpha_iv_i$.

#### (g) Try to explain the deblurring example using the results above. Assume that the noise in the image corresponds to a singular vector $u_i$ with a small corresponding singular value $σ_i$.<br>

Answer:

Since we found that $\hat{x} = \sum_{i=1}^{min(m,n)} \frac{1}{\sigma_i}α_iv_i$ for the regular case, and $\hat{x} = \sum_{i=1}^{min(m,n)} \frac{σ_i}{σ^2_i+\lambda}\alpha_iv_i$ for the regularized case, we can assume the reason that for the ragular case, very small values of $σ_i$ might produce an amplified version of the noise, and thus producing a completely noisy image as shown in the example. On the other hand when adding the $\lambda$ regularization term, and thus prevening this 'explosion'. 

### 4. Camera Calibration

Let  $K = \begin{bmatrix}
    f_x & 0 & x_0 \\
    0 & f_y & y_0 \\
    0 & 0 & 1
\end{bmatrix}$, note that $b = K\begin{bmatrix}
    x \\
    y \\
    z
\end{bmatrix} = \begin{bmatrix}
    x \cdot f_x + z \cdot x_0 \\
    y\cdot f_y + y_0 \cdot z \\
    z
\end{bmatrix}$. therefore $ \begin{bmatrix}
    u \\
    v
\end{bmatrix}$ = $ \begin{bmatrix}
    x \cdot f_x + z \cdot x_0 \\
    y\cdot f_y + y_0 \cdot z
\end{bmatrix}$

As disscused with the TA, we ignore the last entry representing the 3rd dimension. 

#### (a) What is the minimal number of correspondences required to find K?

since we have 4 parmters ($f_x, x_0, y_0, f_y$), we have a solution if the rank of the samples is up to 2 (each correspondent gives us two equations), so if we have 2 (independent) samples we can solve this problme using Gaussian elimination.

#### (b) Assuming the number of correspondences, n, is larger than the minimum number you found in the previous section, how would you solve the problem to obtain a good solution for K?<br>Show all your computations and derivations for the optimal solution in a least squares sense.

If the rank of the samples more then 4, we dont have solution for this problem. we use LSM 
we mark the error of the LSM as:
<br>
$ Err(𝑓_𝑥, x_0, f_y, y_0) = \sum_{i=1}^n || (u_i, v_i) - (x_i \cdot f_x + z_i \cdot x_0,  y_i\cdot f_y + y_0 \cdot z_i) ||^2_2 $ = $\sum_{i=1}^n (u_i - x_i \cdot f_x + z_i \cdot x_0) ^2 + (v_i -  y_i\cdot f_y + y_0 \cdot z_i)^2$
<br>
wherr $n$ is the number of the smaples

Our goal is to find $𝑓_𝑥^*, x_0^*, f_y^*, y_0^*$ = argmin$_{𝑓_𝑥, x_0, f_y, y_0} Err(𝑓_𝑥, x_0, f_y, y_0)$

we compute the derivative and find $Err$ minimum: 
<br>
$\frac{\partial Err}{\partial f_x} = -\sum_{i=1}^n 2(u_i - f_xx_i - z_ix_0) x_i = 2(\sum_{i=1}^n u_ix_i - f_x\sum_{i=1}^n x_i^2 - x_0\sum_{i=1}^n z_ix_i )$ 
<br>
$\frac{\partial Err}{\partial x_0} = -\sum_{i=1}^n 2(u_i - f_xx_i - z_ix_0) z_i = 2(\sum_{i=1}^n u_iz_i - f_x\sum_{i=1}^n z_ix_i - x_0\sum_{i=1}^n z_i^2)$ 
<br>
$\frac{\partial Err}{\partial f_y} = -\sum_{i=1}^n 2(v_i - f_yy_i - z_iy_0) y_i = 2(\sum_{i=1}^n v_iy_i - f_y\sum_{i=1}^n y_i^2 - y_0\sum_{i=1}^n z_iy_i)$
<br>
$\frac{\partial Err}{\partial y_0} = -\sum_{i=1}^n 2(v_i - f_yy_i - z_iy_0) z_i = 2(\sum_{i=1}^n v_iz_i - f_y\sum_{i=1}^n z_iy_i - y_0\sum_{i=1}^n z_i^2)$ 

note:
<br>
$A = \sum_{i=1}^n x_i^2, B = \sum_{i=1}^n z_ix_i, C = \sum_{i=1}^n u_ix_i, D = \sum_{i=1}^n z_i^2, E=\sum_{i=1}^n z_iu_i$
<br>
$F = \sum_{i=1}^n v_iy_i, G = \sum_{i=1}^n y_i^2, H = \sum_{i=1}^n z_iy_i, I = \sum_{i=1}^n v_iz_i$
<br>
Therefore the normal equations are:
<br>
(1) $ Af_x + Bx_0 = C $
<br>
(2) $ Bf_x + Dx_0 = E $
<br>
(3) $ Gf_y + Hy_0 = F$
<br>
(4) $ Hf_y + Dy_0 = I $

and the rseults are:
<br>
    $x_0 = \frac{EA}{B^2 + C + DA}$   
<br>
    $f_x = \frac{Bx_0 + C}{A}$
<br>
    $y_ 0 = \frac{IG}{H^2 + F + DG}$  
<br>
    $f_y =  \frac{Hy_0 + F}{G}$    